import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { ApplicationConfig, importProvidersFrom, inject, provideAppInitializer } from '@angular/core';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideRouter, withComponentInputBinding, withInMemoryScrolling } from '@angular/router';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  Bell,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  Compass,
  Crown,
  Edit3,
  FileText,
  Flag,
  Gem,
  Heart,
  Home,
  Loader2,
  Lock,
  LogOut,
  LucideAngularModule,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Pencil,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  Ruler,
  Save,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Star,
  Upload,
  User,
  UserPlus,
  X,
  Zap
} from 'lucide-angular';
import { routes } from './app.routes';
import { authInterceptor } from './core/auth/auth.interceptor';
import { SessionStore } from './core/auth/session.store';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(
      routes,
      withComponentInputBinding(),
      withInMemoryScrolling({ scrollPositionRestoration: 'top' })
    ),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAppInitializer(() => inject(SessionStore).restore()),
    provideAnimationsAsync(),
    importProvidersFrom(LucideAngularModule.pick({
      AlertCircle,
      AlertTriangle,
      ArrowLeft,
      ArrowRight,
      Ban,
      Bell,
      Calendar,
      Check,
      CheckCheck,
      ChevronDown,
      Compass,
      Crown,
      Edit3,
      FileText,
      Flag,
      Gem,
      Heart,
      Home,
      Loader2,
      Lock,
      LogOut,
      Mail,
      MapPin,
      Menu,
      MessageCircle,
      MessageSquare,
      Pencil,
      RefreshCcw,
      RefreshCw,
      RotateCcw,
      Ruler,
      Save,
      Send,
      Settings,
      Shield,
      ShieldAlert,
      ShieldCheck,
      Sparkles,
      Star,
      Upload,
      User,
      UserPlus,
      X,
      Zap
    }))
  ]
};
