import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { ApplicationConfig, importProvidersFrom, inject, provideAppInitializer } from '@angular/core';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideRouter, withComponentInputBinding, withInMemoryScrolling } from '@angular/router';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Ban,
  Bell,
  Calendar,
  Check,
  CheckCheck,
  ChevronDown,
  Cloud,
  CloudCheck,
  Compass,
  Crown,
  Dumbbell,
  Edit3,
  FileText,
  Flag,
  Flame,
  Gem,
  Heart,
  HeartOff,
  Home,
  Loader2,
  Lock,
  LogOut,
  LucideAngularModule,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  MessageSquare,
  Music,
  Pencil,
  PersonStanding,
  RefreshCcw,
  RefreshCw,
  RotateCcw,
  Ruler,
  Save,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Star,
  Trash2,
  Upload,
  User,
  UserPlus,
  Users,
  X,
  Zap
} from 'lucide-angular';
import { routes } from './app.routes';
import { authInterceptor } from './core/auth/auth.interceptor';
import { SessionStore } from './core/auth/session.store';

export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(
      routes,
      withComponentInputBinding(),
      withInMemoryScrolling({ scrollPositionRestoration: 'top' })
    ),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideAppInitializer(() => inject(SessionStore).restore()),
    provideAnimationsAsync(),
    importProvidersFrom(LucideAngularModule.pick({
      AlertCircle,
      AlertTriangle,
      ArrowLeft,
      ArrowRight,
      Ban,
      Bell,
      Calendar,
      Check,
      CheckCheck,
      ChevronDown,
      Cloud,
      CloudCheck,
      Compass,
      Crown,
      Dumbbell,
      Edit3,
      FileText,
      Flag,
      Flame,
      Gem,
      Heart,
      HeartOff,
      Home,
      Loader2,
      Lock,
      LogOut,
      Mail,
      MapPin,
      Menu,
      MessageCircle,
      MessageSquare,
      Music,
      Pencil,
      PersonStanding,
      RefreshCcw,
      RefreshCw,
      RotateCcw,
      Ruler,
      Save,
      Send,
      Settings,
      Shield,
      ShieldAlert,
      ShieldCheck,
      Sparkles,
      Star,
      Trash2,
      Upload,
      User,
      UserPlus,
      Users,
      X,
      Zap
    }))
  ]
};
