package com.himeros.profile;
import jakarta.persistence.*; import java.time.*; import java.util.*;
@Entity @Table(name="profiles")
public class Profile {
 @Id @Column(name="user_id") private UUID userId; @Column(name="display_name",nullable=false,length=80) private String displayName; @Column(length=1000) private String bio; @Column(name="birth_date",nullable=false) private LocalDate birthDate; @Enumerated(EnumType.STRING) @Column(nullable=false) private Gender gender;
 private String city; private String state; private String country; private Double latitude; private Double longitude; @Column(name="min_age",nullable=false) private int minAge; @Column(name="max_age",nullable=false) private int maxAge; @Column(name="max_distance_km",nullable=false) private int maxDistanceKm; @Column(nullable=false) private boolean discoverable;
 @ElementCollection(fetch=FetchType.EAGER) @CollectionTable(name="profile_interests",joinColumns=@JoinColumn(name="user_id")) @Column(name="interest") private Set<String> interests=new HashSet<>();
 @ElementCollection(fetch=FetchType.EAGER) @CollectionTable(name="profile_looking_for",joinColumns=@JoinColumn(name="user_id")) @Column(name="gender") @Enumerated(EnumType.STRING) private Set<Gender> lookingFor=new HashSet<>();
 @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt;
 protected Profile(){}
 public Profile(UUID userId,String displayName,LocalDate birthDate,Gender gender){this.userId=userId;this.displayName=displayName;this.birthDate=birthDate;this.gender=gender;this.minAge=18;this.maxAge=99;this.maxDistanceKm=100;this.discoverable=true;this.createdAt=Instant.now();this.updatedAt=createdAt;}
 public void update(String name,String bio,LocalDate birth,Gender gender,String city,String state,String country,Double lat,Double lon,int minAge,int maxAge,int maxDistance,boolean discoverable,Set<String> interests,Set<Gender> lookingFor){this.displayName=name;this.bio=bio;this.birthDate=birth;this.gender=gender;this.city=city;this.state=state;this.country=country;this.latitude=lat;this.longitude=lon;this.minAge=minAge;this.maxAge=maxAge;this.maxDistanceKm=maxDistance;this.discoverable=discoverable;this.interests=new HashSet<>(interests==null?Set.of():interests);this.lookingFor=new HashSet<>(lookingFor==null?Set.of():lookingFor);this.updatedAt=Instant.now();}
 public UUID getUserId(){return userId;} public String getDisplayName(){return displayName;} public String getBio(){return bio;} public LocalDate getBirthDate(){return birthDate;} public Gender getGender(){return gender;} public String getCity(){return city;} public String getState(){return state;} public String getCountry(){return country;} public Double getLatitude(){return latitude;} public Double getLongitude(){return longitude;} public int getMinAge(){return minAge;} public int getMaxAge(){return maxAge;} public int getMaxDistanceKm(){return maxDistanceKm;} public boolean isDiscoverable(){return discoverable;} public Set<String> getInterests(){return Set.copyOf(interests);} public Set<Gender> getLookingFor(){return Set.copyOf(lookingFor);}
}
