package com.himeros.profile;
import jakarta.persistence.*; import java.time.*; import java.util.*; import org.hibernate.annotations.BatchSize;
@Entity @Table(name="profiles")
public class Profile {
 @Id @Column(name="user_id") private UUID userId; @Column(name="display_name",nullable=false,length=80) private String displayName; @Column(length=1000) private String bio; @Column(name="birth_date",nullable=false) private LocalDate birthDate; @Enumerated(EnumType.STRING) @Column(nullable=false) private Gender gender;
 @Enumerated(EnumType.STRING) @Column(name="body_type") private BodyType bodyType;
 private String city; private String state; private String country; private Double latitude; private Double longitude; @Column(name="min_age",nullable=false) private int minAge; @Column(name="max_age",nullable=false) private int maxAge; @Column(name="max_distance_km",nullable=false) private int maxDistanceKm; @Column(name="strict_age",nullable=false) private boolean strictAge; @Column(name="strict_distance",nullable=false) private boolean strictDistance; @Column(nullable=false) private boolean discoverable; @Column(name="recently_active_first",nullable=false) private boolean recentlyActiveFirst; @Column(name="global_mode",nullable=false) private boolean globalMode;
 @ElementCollection(fetch=FetchType.LAZY) @BatchSize(size=100) @CollectionTable(name="profile_interests",joinColumns=@JoinColumn(name="user_id")) @Column(name="interest") private Set<String> interests=new HashSet<>();
 @ElementCollection(fetch=FetchType.LAZY) @BatchSize(size=100) @CollectionTable(name="profile_looking_for",joinColumns=@JoinColumn(name="user_id")) @Column(name="gender") @Enumerated(EnumType.STRING) private Set<Gender> lookingFor=new HashSet<>();
 @ElementCollection(fetch=FetchType.LAZY) @BatchSize(size=100) @CollectionTable(name="profile_preferred_body_types",joinColumns=@JoinColumn(name="user_id")) @Column(name="body_type") @Enumerated(EnumType.STRING) private Set<BodyType> preferredBodyTypes=new HashSet<>();
 @Column(name="created_at",nullable=false) private Instant createdAt; @Column(name="updated_at",nullable=false) private Instant updatedAt; @Column(name="last_active_at",nullable=false) private Instant lastActiveAt;
 protected Profile(){}
 public Profile(UUID userId,String displayName,LocalDate birthDate,Gender gender){this.userId=userId;this.displayName=displayName;this.birthDate=birthDate;this.gender=gender;this.minAge=18;this.maxAge=99;this.maxDistanceKm=100;this.strictAge=false;this.strictDistance=false;this.discoverable=true;this.recentlyActiveFirst=false;this.globalMode=false;this.createdAt=Instant.now();this.updatedAt=createdAt;this.lastActiveAt=createdAt;}
 public void update(String name,String bio,LocalDate birth,Gender gender,BodyType bodyType,String city,String state,String country,Double lat,Double lon,int minAge,int maxAge,int maxDistance,boolean strictAge,boolean strictDistance,boolean discoverable,boolean recentlyActiveFirst,boolean globalMode,Set<String> interests,Set<Gender> lookingFor,Set<BodyType> preferredBodyTypes){this.displayName=name;this.bio=bio;this.birthDate=birth;this.gender=gender;this.bodyType=bodyType;this.city=city;this.state=state;this.country=country;this.latitude=lat;this.longitude=lon;this.minAge=minAge;this.maxAge=maxAge;this.maxDistanceKm=maxDistance;this.strictAge=strictAge;this.strictDistance=strictDistance;this.discoverable=discoverable;this.recentlyActiveFirst=recentlyActiveFirst;this.globalMode=globalMode;this.interests=new HashSet<>(interests==null?Set.of():interests);this.lookingFor=new HashSet<>(lookingFor==null?Set.of():lookingFor);this.preferredBodyTypes=new HashSet<>(preferredBodyTypes==null?Set.of():preferredBodyTypes);this.updatedAt=Instant.now();this.lastActiveAt=this.updatedAt;}
 public UUID getUserId(){return userId;} public String getDisplayName(){return displayName;} public String getBio(){return bio;} public LocalDate getBirthDate(){return birthDate;} public Gender getGender(){return gender;} public BodyType getBodyType(){return bodyType;} public String getCity(){return city;} public String getState(){return state;} public String getCountry(){return country;} public Double getLatitude(){return latitude;} public Double getLongitude(){return longitude;} public int getMinAge(){return minAge;} public int getMaxAge(){return maxAge;} public int getMaxDistanceKm(){return maxDistanceKm;} public boolean isStrictAge(){return strictAge;} public boolean isStrictDistance(){return strictDistance;} public boolean isDiscoverable(){return discoverable;} public boolean isRecentlyActiveFirst(){return recentlyActiveFirst;} public boolean isGlobalMode(){return globalMode;} public Set<String> getInterests(){return Set.copyOf(interests);} public Set<Gender> getLookingFor(){return Set.copyOf(lookingFor);} public Set<BodyType> getPreferredBodyTypes(){return Set.copyOf(preferredBodyTypes);} public Instant getCreatedAt(){return createdAt;} public Instant getUpdatedAt(){return updatedAt;} public Instant getLastActiveAt(){return lastActiveAt;}
}
