package com.himeros.messaging;
import com.himeros.match.MatchCreated;import com.himeros.shared.*;import com.himeros.shared.outbox.OutboxService;import java.time.Instant;import java.util.*;import org.springframework.data.domain.PageRequest;import org.springframework.messaging.simp.SimpMessagingTemplate;import org.springframework.context.event.EventListener;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class MessagingService {private final ConversationRepository conversations;private final MessageRepository messages;private final OutboxService outbox;private final SimpMessagingTemplate ws;public MessagingService(ConversationRepository c,MessageRepository m,OutboxService o,SimpMessagingTemplate ws){conversations=c;messages=m;outbox=o;this.ws=ws;}
 @EventListener public void on(MatchCreated e){conversations.findByMatchId(e.matchId()).orElseGet(()->conversations.save(new Conversation(e.matchId(),e.userA(),e.userB())));}
 @Transactional(readOnly=true) public List<ConversationView> list(UUID user){return conversations.findForUser(user).stream().map(MessagingService::view).toList();}
 @Transactional public MessageView send(UUID user,UUID conversationId,String body){Conversation c=owned(user,conversationId);String content=body==null?"":body.trim();if(content.isBlank()||content.length()>4000)throw new IllegalArgumentException("Message must contain 1-4000 characters");Message m=messages.save(new Message(conversationId,user,content));c.touch(m.sent());MessageView result=messageView(m);outbox.append("Message",m.id(),"himeros.messaging.message-sent.v1","himeros.messaging.events.v1",conversationId,Map.of("messageId",m.id(),"conversationId",conversationId,"senderId",user));ws.convertAndSend("/topic/conversations/"+conversationId,result);return result;}
 @Transactional(readOnly=true) public List<MessageView> history(UUID user,UUID conversationId,Instant before,int limit){owned(user,conversationId);var page=PageRequest.of(0,Math.min(Math.max(limit,1),100));return (before==null?messages.latest(conversationId,page):messages.before(conversationId,before,page)).stream().map(MessagingService::messageView).toList();}
 @Transactional public int markRead(UUID user,UUID conversationId){owned(user,conversationId);return messages.markRead(conversationId,user);}
 private Conversation owned(UUID user,UUID id){Conversation c=conversations.findById(id).orElseThrow(()->new ResourceNotFoundException("Conversation not found"));if(!c.contains(user))throw new ForbiddenException("Not your conversation");return c;}
 private static ConversationView view(Conversation c){return new ConversationView(c.id(),c.matchId(),c.a(),c.b(),c.created(),c.last());}private static MessageView messageView(Message m){return new MessageView(m.id(),m.conversation(),m.sender(),m.content(),m.sent(),m.read());}
 public record ConversationView(UUID id,UUID matchId,UUID userA,UUID userB,Instant createdAt,Instant lastMessageAt){} public record MessageView(UUID id,UUID conversationId,UUID senderId,String content,Instant sentAt,Instant readAt){}
}
