### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{"email":"alice@example.com","password":"ChangeMe123!"}

### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{"email":"alice@example.com","password":"ChangeMe123!"}

### Health
GET http://localhost:8080/actuator/health
